services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=ecommerce_backend.settings
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ecommerce
      - DEBUG=0
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  test:
    build: .
    profiles: ["test"]
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=ecommerce_backend.settings
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ecommerce
      - DEBUG=0
    volumes:
      - .:/app
    entrypoint: python manage.py test orders -v 2

volumes:
  postgres_data: 